[project]
name = "nix-toolbox"
version = "0.1.0"
description = "Nix Toolbox Documentation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]
