---
name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  mkdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          python -m pip install --upgrade uv

      - name: Install make
        run: |
          sudo apt-get update && sudo apt-get install -y make

      - name: Build MkDocs site
        run: make docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
          publish_branch: ${{ github.event_name == 'pull_request' && format('gh-pages-pr-{0}', github.event.pull_request.number) || 'gh-pages' }}
          keep_files: true
